### ISSUE TITLE
Functionality proposal

### ISSUE THREAD

**Issue by sum1afk** [lodsdev/lua-class#3]
I was working on a scene node class with your library and I don't know if I overlooked some things to access super class info, but I added a few small changes to make a function like this: derivedFrom(instance, "ClassName")
I need this functionality to check if a child being added to a node is either another scene node or derived from another scene node. 
I know you can access __name or superClass.__name directly, but I thought this is more elegant and consistent with the existing functionality
If this is helpful or unnecessary or both, or broken, let me know
Here's the modified code snippets in my version:

bad code removed. 
Find in pull request

**Comment by lodsdev** [comment]
that sounds good
